# Generated by Django 5.0.2 on 2024-04-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['title']},
        ),
    ]
