# Generated by Django 5.0.2 on 2024-04-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_alter_variant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['product']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product']},
        ),
    ]
